### ISSUE TITLE
palatals, alveolopalatals, and palatalized alveolars

### ISSUE THREAD

**Issue by chronodm** [notnami/phonemes#5]
/ɕ/ and /ʃʲ/ are both given as “voiceless alveolo-palatal sibilant” with the same features. From /ʃ/, it seems as though /ʃʲ/ should be “palatalized voiceless *palato-alveolar* sibilant”, although I admit I'm not sure how I'd hear (or produce) the difference. (/ʃ/ is also `-strident` — maybe /ʃʲ/ should be as well?)

It looks like you're modeling palatalization as `+dorsal, +high`, is that correct? This leads to a few pairs that can't be distinguished by features:

1. /dʲ/ (palatalised voiced alveolar stop) and /ɾʲ/ (palatalised alveolar flap)
   - /d/ and /ɾ/ differ only in that /d/ is `+dorsal`
2. /ç/ (voiceless palatal fricative) and /ɕ/ (voiceless alveolo-palatal sibilant)
   - plus also /ʃʲ/, although as noted above I suspect it should be `-strident`
3. /ʝ/ (voiced palatal fricative) and /ʑ/ (voiced alveolo-palatal sibilant)
   - voiced counterparts of /ç/ and /ɕ/

For (1), I'm not finding a good canonical explanation in distinctive feature terms of /d/ vs /ɾ/. I found some [lecture notes](https://msu.edu/course/lin/401/fs03-s2/distinctive.pdf) from Michigan State that give /ɾ/ as `+cont`, although I find that a little suspect. [This undergraduate paper](http://seas3.elte.hu/odd/odd9/02_PANDI_Julianna.pdf) by Julianna Sarolta Pándi suggests it's a fool's errand and that none of the schemes the author's found are satisfactory, for various compelling reasons. (The `+cont` analysis, for instance, might make sense analying the tap vs. trill contrast in Spanish but isn't much use when looking at the flapping of alveolar stops in American English).

For (2) and (3), it doesn't seem like as hopeless a cause, but I'm still not able to come up with a canonical answer. The distinction between /ɕ/ and /ç/ isn't clear in Jason Riggle's chart -- neither in place (alveolo-palatal vs. palatal) or manner (sibilant vs. non-sibilant). [Olga Arnaudova](http://aix1.uottawa.ca/~oarnaou/distinctive.htm) has palatals as `-coronal`, contra Riggle, and has palato-alveolars as `+coronal`, but doesn't address the coronality of alveolo-palatals. (She has palato-alveolars as `+strident` and alveolo-palatals as `-strident`). She also doesn't address siblance. [Daniel Recasens](http://pagines.uab.cat/danielrecasens/sites/pagines.uab.cat.danielrecasens/files/Alveolopalatals%20JIPA.pdf) cites Ladefoged to the effect that “segments … are expected to be either coronal or dorsal, and the corresponding places of articulation alveolar or postalveolar if the segment is coronal and palatal if the segment is dorsal”. This would also suggest /ç/ should be `-coronal` (cf. Arnaudova above). (Recasens, while arguing for IPA to incorporate a clear distinction between palatal and alveolopalatal, also says that /ɕ/ is “realized more often with a postalveolar articulation than with an alveolopalatal one.”) Maybe we should ask Riggle what he thinks.

So apart from the idea that /ʃʲ/ should be renamed and `-strident`, I don't have any concrete suggestions. (I can submit a pull request for that if you agree.) Am I right in thinking /dʲ/–/ɾʲ/, /ç/–/ɕ/ and /ʝ/–/ʑ/ are more a matter of taste/convenience, and just more or less intractable in terms of features?

**Comment by anna-hope** [comment]
Thanks for this analysis.

Indeed, I agree that an alveolar tap should not be given as `+cont`, because if it were continuous, it would be a trill.

As you might have noticed, Jason Riggle's original chart does not have any palatalised consonants. [Rafael Abramovitz](http://linguistics.mit.edu/user/rafabr/) and I had to come up with a way to encode those for a project we were working on. At the time, we could not get any input from JR. We were definitely not sure that the way we encoded them was 100% correct, but it served our needs at the time, and that's what made it into this repository.

"Maybe we should ask Riggle what he thinks."

Ha. If you're at UChicago, you can try catching him in his office or obtain his schedule and stalk JR after class. Otherwise, getting in touch with him is near impossible -- he almost never replies to emails. But you are welcome to try and report back with results!

"(/ʃ/ is also -strident — maybe /ʃʲ/ should be as well?)"

I think it's actually us giving /ʃ/ as `-strident` that is a mistake, because a sibilant is [by definition a strident](https://en.wikipedia.org/wiki/Sibilant). So, if you could submit a PR to fix that, I would appreciate it!

"Am I right in thinking /dʲ/–/ɾʲ/, /ç/–/ɕ/ and /ʝ/–/ʑ/ are more a matter of taste/convenience, and just more or less intractable in terms of features?"

It would seem to me that JR's chart simply does not provide enough binary features for us to encode all of these sounds perfectly. I don't know how to solve that, other than if we have input from a phonetician or find a relevant thesis/paper that resolves all of these conflicts.

**Comment by chronodm** [comment]
> I think it's actually us giving /ʃ/ as -strident that is a mistake, because a sibilant is by definition a strident. So, if you could submit a PR to fix that, I would appreciate it!

Good catch, & can do. Shall I rename /ʃʲ/ while I'm at it?

**Comment by anna-hope** [comment]
Yes, thanks.

**Comment by chronodm** [comment]
Done. I'll close this. I posted a question on [Linguistics StackExchange](http://linguistics.stackexchange.com/questions/21033/is-there-a-distinctive-feature-that-separates-alveolo-palatals-from-palatals); if anything useful comes of it I can open another issue.

**Comment by anna-hope** [comment]
Actually, I would leave this open, because the broader questions remain to be answered.

**Comment by chronodm** [comment]
So (coming back to this after considerable time away), Wikipedia suggests /[ɕ](https://en.wikipedia.org/wiki/Voiceless_alveolo-palatal_sibilant)/ is `+strident`, which would differentiate it from /[ç](https://en.wikipedia.org/wiki/Voiceless_palatal_fricative)/, and instead have it collide with /ʃʲ/.

I think this might actually be correct, given the examples in the [Japanese phonology](https://en.wikipedia.org/wiki/Japanese_phonology#Palatalization_and_affrication) article—I used to be moderately fluent in Japanese, with a pretty good accent, and there’s definitely a distinction between the palatalized /s/ they give as [ɕ] and the palatalized /h/ they give as [ç].

The Wikipedia article on [alveolo-palatal consonants](https://en.wikipedia.org/wiki/Alveolo-palatal_consonant#Sibilants) also says:

> The letters ⟨ɕ⟩ and ⟨ʑ⟩ are essentially equivalent to ⟨ ʃʲ⟩ and ⟨ʒʲ⟩. They are the sibilant homologues of the pre-palatal fricatives [ç˖] and [ʝ˖].

So I propose making /ɕ/ `+strident`. If we make its voiced counterpart /[ʑ](https://en.wikipedia.org/wiki/Voiced_alveolo-palatal_sibilant)/, that also solves the collision of /ʑ/ and /ʝ/. (Presumably it would then collide with /ʒʲ/, but /ʒʲ/ isn't in the table, so that's in the clear. Although one could also consider adding it—with features identical to the now-strident /ʑ/.)

**Comment by anna-hope** [comment]
Okay, please send a pull request.
